# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WWDC17' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WWDC17
  pod 'LTMorphingLabel'

  target 'WWDC17Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WWDC17UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
